### ISSUE TITLE
Bloodpacts getting spammed

### ISSUE THREAD

**Issue by roneeh** [Mykezero/EasyFarm#88]
Bloodpacts are getting spammed due to wrong information in resource files? 

Thanks a lot for your great work! ^.~

**Comment by Mykezero** [comment]
I've fixed the problem. The next update should fix this issue. The resource files were fine but the code that handles recasts had to be adjusted specifically for summoner's bloodpact job abilities.

**Comment by roneeh** [comment]
Thanks a lot!

Thanks for your hard work. :')
